-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 10:26:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatbox` DEFAULT CHARACTER SET utf8 ;
USE `chatbox` ;

-- -----------------------------------------------------
-- Table `chatbox`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbox`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `last_logout` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatbox`.`MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatbox`.`MESSAGE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MESSAGE_USER1_idx` (`user_id` ASC),
  CONSTRAINT `fk_MESSAGE_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `chatbox`.`USER` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
